### ISSUE TITLE
After file open, diagnostics doesn't showed on editor pane and no squiggly line file

### ISSUE THREAD

**Issue by iitaiy** [microsoft/qsharp-compiler#556] opened 2020-08-06 14:16 UTC
**Describe the bug**

When opening a file on Visual Studio 2019 with diagnostics, the diagnostics appear on the error list window but there is no squiggly line or any indication on the file editor pane.

**To Reproduce**

1. Create a new Qsharp project.
2. Open the Program.qs file.
3. Delete the semicolon from line 9 (`Message("Hello quantum world!");` -> `Message("Hello quantum world!")`).
4. Close the file.
5. Open the file again.

**Expected behavior**

A squiggly line under the missing semicolon and indication on the editor pane.

**Screenshots**

![image](https://user-images.githubusercontent.com/23120909/89542215-0a28b780-d808-11ea-9b46-71b6abc7f656.png)

**System information**

- NuGet package version: 0.12.2007.2031
- OS: Windows 10, .Net Core 3.1.301
- IDE: Visual Studio Enterprise 2019, version 16.6.2

**Comment by samarsha** [comment] 2020-08-06 18:30
Hello, thanks for your bug report! I tried this with Visual Studio 16.6.5 and QDK extension 0.12.2007.2031, and the red squiggly shows up for me. Just as a quick check, could you try showing the line and column numbers in the error list?

![image](https://user-images.githubusercontent.com/33814365/89568067-9a9ad400-d7d7-11ea-9d2e-44d541727f68.png)

(Sorry about the German - "Zeile" and "Spalte" should be "Line" and "Column" in English.) If they show up correctly as 9 and 40 for you, it seems like the Q# language server is making diagnostics correctly. Maybe it's a Visual Studio display problem? You could also check the "Q# Language Extension" section in the "Output" tab - there shouldn't be an errors there:

![image](https://user-images.githubusercontent.com/33814365/89568375-11d06800-d7d8-11ea-9277-554c44bd4ea6.png)

**Comment by iitaiy** [comment] 2020-08-06 21:14
Thank you for the quick response.

I tried to update to VS 16.7.0 and I get the same result with more diagnostics:
![image](https://user-images.githubusercontent.com/23120909/89583240-ab346400-d842-11ea-9372-16208a15ddc6.png)

Output window:
![image](https://user-images.githubusercontent.com/23120909/89583329-ce5f1380-d842-11ea-8244-7f100bda67da.png)

**Comment by samarsha** [comment] 2020-08-06 21:49
Hmm, I get the same errors after upgrading to VS 16.7.0 (although I see red squigglies for them). I think it's related to the upgrade to .NET Core 3.1.400. I created issue #558 for it since I think it is separate from the red squigglies not showing.

Pinging @bettinaheim and @ricardo-espinoza since I'm not that familiar with the Visual Studio extension.

One thing you could try is to reset your Visual Studio settings. In the "Tools" menu, there should be an item "Import and Export Settings." I think you can export your settings to a file before resetting them if you have any customization you want to keep. Then there should be a "reset all settings" option at the bottom of the import/export window.

**Comment by samarsha** [comment] 2020-10-09 16:42
Hi @iitaiy, just wanted to follow up and see if you were still experiencing this issue. If you are, did you have a chance to try resetting your Visual Studio settings?

**Comment by samarsha** [comment] 2020-10-30 22:35
Closing for now since there isn't enough information for me to reproduce the issue, but please let me know if the issue is still happening. Thank you!

**Closed by samarsha** 2020-10-30 22:35 UTC
Labels: Area-IDE, bug, needs info
