### ISSUE TITLE
Lambda Type Inference not working for Fold

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-compiler#1383] opened 2022-03-21 20:44 UTC
**Describe the bug**

The Q# type inference should be able to infer type parameters for the Fold function when that function is given a lambda. It doesn't seem to be able to do this.

**To Reproduce**

```qsharp
let intArray = [14, 15, 3, -4, 18];
let sum = Fold((x, y) -> x + y, 0, intArray);
```

The following error is given:
```
QS5006 The type 'c does not support the + operator.
```

The issue goes away when type parameters are provided explicitly:
```qsharp
let intArray = [14, 15, 3, -4, 18];
let sum = Fold<Int,Int>((x, y) -> x + y, 0, intArray);
```

**Expected behavior**

The type inference should be able to infer the proper type for the Fold function without the need to specify the types manually.

**System information**

- QDK version 0.23.195983

**Comment by ScottCarda-MS** [comment] 2022-03-21 20:44
@samarsha could you look into this please?

**Comment by samarsha** [comment] 2022-03-21 21:14
I can reproduce the bug with version 0.23.195983, and commit abd3b23, but it seems to be fixed starting with commit 8c57aa0. So it seems like it was accidentally fixed by #1344.

**Comment by ScottCarda-MS** [comment] 2022-03-21 21:25
Already fixed.

**Comment by samarsha** [comment] 2022-03-21 21:28
We should add a test case for this.

**Closed** 2022-03-23 19:48 UTC
Labels: bug, area: type system
