### ISSUE TITLE
Q# SDK support for dotnet 5

### ISSUE THREAD

**Issue by spotakash** [microsoft/qsharp-compiler#883] opened 2021-02-26 12:53 UTC
Have been testing this https://docs.microsoft.com/en-gb/learn/modules/qsharp-create-first-quantum-development-kit/2-install-quantum-development-kit-code when start using Q# SDK it starts throwing error that donet 3.1 could not find while 5.0.2 is installed and detected. 
  The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
    - The following frameworks were found:
        5.0.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by samarsha** [comment] 2021-03-02 23:18
At the moment, the QDK requires .NET Core 3.1. You can still have .NET 5 installed, but the .NET Core 3.1 SDK also needs to be installed along side it.

**Comment by samarsha** [comment] 2021-03-02 23:23
Duplicate of #737

**Closed by samarsha** 2021-03-02 23:23 UTC
Labels: enhancement
