### ISSUE TITLE
[] should create an empty array

### ISSUE THREAD

**Issue by guenp** [microsoft/qsharp-compiler#617] opened 2020-09-10 16:21 UTC
**Is your feature request related to a problem? Please describe.**
When I create an array, I can use square brackets like so: `[1, 2, 3]`.
However, when I try to make an empty array like so: `[]`, I get an error saying that I should use `new 'T[0]`.

**Describe the solution you'd like**
I would like to be able to define an empty array using `[]`

**Describe alternatives you've considered**
Another library function called `EmptyArray`, which may be easier than `new 'T[0]`.

**Additional context**
We discussed `EmptyArray` during the `Microsoft.Quantum.Arrays` API review on 9/10/2020 and the conclusion was to implement `EmptyArray` but also file this issue.

**Comment by samarsha** [comment] 2020-09-10 20:23
Yes, this would be great. We will probably need to improve Q#'s type inference for this to work best. Without better type inference, we could also consider making it possible to specify types of expressions with `:`, e.g. `let xs = [] : Int[]` would be equivalent to `let xs = EmptyArray<Int>()`.

**Comment by cgranade** [comment] 2020-09-10 22:19
One place where type inference could really help is in when an array of arrays contains an empty array as an element:

```
let indices = [
    [0],
    [0, 10, 3],
    [] // oops
];
```

**Comment by msoeken** [comment] 2020-09-11 07:46
I strongly support this proposal. We should be able to deduce the type when passing an array to a function or operation:

```
let zero = Length<Int>([]);
(Controlled X)([], target);
```

We already have similar partial deduction in place for open ranges such as `values[5...]`, but I cannot write `let numbers = 5...`.

**Comment by samarsha** [comment] 2020-09-11 16:07
> We already have similar partial deduction in place for open ranges such as `values[5...]`, but I cannot write `let numbers = 5...`.

Hmm, not related to this issue, but I feel like you should be able to write `5...` in any context and have it evaluate to the infinite range `5, 6, 7, ...`. That would be consistent with current array slicing behavior if we allow ranges to extend beyond the size of an array (currently that's an index out of range error, but I feel like that's unnecessary).

**Comment by cgranade** [comment] 2020-09-11 16:40
> > We already have similar partial deduction in place for open ranges such as `values[5...]`, but I cannot write `let numbers = 5...`.
> 
> Hmm, not related to this issue, but I feel like you should be able to write `5...` in any context and have it evaluate to the infinite range `5, 6, 7, ...`. That would be consistent with current array slicing behavior if we allow ranges to extend beyond the size of an array (currently that's an index out of range error, but I feel like that's unnecessary).

I personally tend to think of `Range` as a kind of UDT (indeed, I think it could be really cool to literally make that the case, so that we no longer need `RangeStart`, `RangeStop` and `RangeStep` to be separate functions, and can just use `(1..3)::Step` directly). From that perspective, infinite ranges sound like a UDT with optional start and stop (assuming DUs and type-parameterized UDTs):

```
namespace Microsoft.Quantum.Core {
    newtype Range = (
        Start: Optional<Int>,
        Step: Int,
        Stop: Optional<Int>
    );
}
```

The two would thus be equivalent:
```
let foo = arr[3...];
let foo = arr[Range(Some(3), 1, None<Int>())];
```

**Comment by samarsha** [comment] 2020-09-11 16:47
I forgot about the range start being optional... what is the first number that this code prints?

```qsharp
for (i in Range(None(), 1, 10)) {
    Message($"{i}");
}
```

**Comment by cgranade** [comment] 2020-09-11 16:49
Oh, no.

**Comment by samarsha** [comment] 2020-09-11 19:37
> More seriously, we already require that `for` loops are finite in extent for adjointability. Could we make the it such that you can store an open-ended `Range` as a variable, but can't then use that variable in a `for` loop?

To verify adjointability at compile time, would infinite ranges have a different type than finite ranges?

**Comment by cgranade** [comment] 2020-09-16 22:22
Assuming #557, you could introduce a new type without too much difficulty and then use concepts to provide a consistent way of using either closed or open ranges.

```
newtype Range = (
    Start: Int,
    Step: Int,
    Stop: Int
);

newtype OpenRange = (
    Start: Optional<Int>,
    Step: Int,
    Stop: Optional<Int>
);

concept 'Self is SubscriptableBy<'Index, 'Result> when {
     function ([])(self : 'Self, index : 'Index) : 'Result;
}

example 'T[] of SubscriptableBy<Int, 'T> {
     function ([])(self : 'T[], index : Int) : 'T {
         body intrinsic;
     }
}

example 'T[] of SubscriptableBy<Range, 'T[]> {
     function ([])(self : 'T[], index : Range) : 'T[] {
         body intrinsic;
     }
}

example 'T[] of SubscriptableBy<OpenRange, 'T[]> {
     function ([])(self : 'T[], index : OpenRange) : 'T[] {
         body intrinsic;
     }
}

// alternative definitions for OpenRange:
newtype OpenRange =
    LeftOpen(Step : Int, Stop : Int) |
    RightOpen(Start : Int, Step : Int) |
    // Here, Representative is any member of the open range.
    // E.g.: Open(1, 2) is all odd integers, while
    // Open(2, 7) is all integers equal to 2 mod 7.
    Open(Representative : Int, Step : Int);

// examples
let all = ...1...; // Open(0, 1)
let foo = arr[all]; // identical to `arr` on its own
let odds = Open(1, 2); // what would shorthand be?
let bar = arr[odds]; // identical to `arr[1...2...]`, since range truncated on the left by zero.
```

**Comment by samarsha** [comment] 2021-02-13 19:10
Duplicate of #857. This has been approved in [QEP 2](https://github.com/microsoft/qsharp-language/blob/main/Approved/2-enhanced-array-literals.md), so closing this in favor of the QEP 2 tracking issue instead.

**Closed by samarsha** 2021-02-13 19:10 UTC
Labels: area: language, enhancement
