### ISSUE TITLE
Older version of VSCode extension cannot recognize newer projects (loads a project and then claims it didn't).

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/qsharp-compiler#870] opened 2021-02-19 06:14 UTC
**Describe the bug**

I can on multiple machines clone this repo (https://github.com/crazy4pi314/qsharp-zne) and try and open it with VS Code and the QKD extension installed and the language service fails to load for the Q# file in the project, after saying it successfully loads it.  The project builds and runs fine, but I get nothing more than syntax highlighting. I created the project with the project templates from the command line.

I can open other projects on the same machines and get the language service working, 

If I look at the output of the language extension it has this:
```
[Info  - 11:18:48 PM] workspace folder: c:\Users\skais\git\crazy4pi314\qsharp-zne
Discovered Q# project 'c:\Users\skais\git\crazy4pi314\qsharp-zne\qsharp-zne.csproj'.
[Info  - 11:19:05 PM] The file c:\Users\skais\git\crazy4pi314\qsharp-zne\Program.qs is not associated with a compilation unit. Only syntactic diagnostics are generated.
```

**To Reproduce**

1. Clone the above repo, and open it with VS Code.

**Expected behavior**

I expected to have the intelsense features that I get in other repos/the language server working.

**System information**

- Version of the NuGet package or extension for which the problem occurs
- Your operating system and .NET Core version  
- For issues with extensions, the version of the IDE for which the problem occurs 

Window Version	10.0.19042 Build 19042

```
dotnet --list-sdks
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
```
VS Code:
```
Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
QDK VSCode extension: v0.15.2102128318

**Additional context**

**Comment by crazy4pi314** [comment] 2021-02-23 02:30
So I have isolated the cause here, and its that when I try to work with a project that has a newer version number of the SDK than the extension was built with it sees the project but won't recognize any of the source files are associated with it. You can reproduce this by taking my example above and rolling the project version back to the same as the extension. I can use this as a work around when I am streaming, let me know if I can help in testing any fixes for this!

**Comment by guenp** [comment] 2021-02-23 23:22
I can confirm @crazy4pi314's observation. I had to downgrade my project to a lower version in order for the language server to pick up my project.

**Comment by bettinaheim** [comment] 2021-02-26 14:24
@crazy4pi314  Thanks for reporting! I am not sure there is any way around that; while we try not to modify how the extensions work, in general there is also not really a way to be "forward compatible". We can make newer versions backward compatible, but we can't really guarantee that older extensions will be able to recognize newer projects. Do you have any suggestions on what you were hoping for?

**Comment by crazy4pi314** [comment] 2021-03-03 01:21
I am not sure I have any suggestions/hopes for different behavior, this is just a hard problem! I mostly just wanted to document it here in case others ran into similar because I thought I was going insane and could never get the language server working on my machines :P

**Comment by bettinaheim** [comment] 2021-03-03 15:06
Thanks for the documentation, that is indeed hopefully helpful to others. Since the resolution for this problem is to update the extension, I will close this issue here.

**Closed by bettinaheim** 2021-03-03 15:06 UTC
Labels: bug
