### ISSUE TITLE
Deprecated functions are not rendered properly in the summary column

### ISSUE THREAD

**Issue by k4rtik** [microsoft/qsharp-compiler#1119] opened 2021-08-09 18:23 UTC
Name | Summary
-- | --
Zip | > [!WARNING]
Zip3 | > [!WARNING]
Zip4 | > [!WARNING]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74478f59-fbc3-32b1-fbcd-52e360d6b101
* Version Independent ID: bd39a2a8-38e3-4824-35ac-bee76bb4498a
* Content: [Microsoft.Quantum.Arrays namespace - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays)
* Content Source: [api/qsharp/microsoft.quantum.arrays.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/qsharp/microsoft.quantum.arrays.md)
* Product: **qsharp**
* GitHub Login: @ricardo-espinoza

**Comment by tcNickolas** [comment] 2021-08-16 21:07
This looks like a duplicate of https://github.com/microsoft/qsharp-compiler/issues/1017.

**Comment by cgranade** [comment] 2021-08-16 21:08
Agreed, let me close this one, then, and mark as a duplicate.

**Closed by cgranade** 2021-08-16 21:08 UTC
Labels: bug, area: docs generation
