### ISSUE TITLE
QSharpDocsOutputPath should not imply QSharpDocsGeneration

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#997] opened 2021-04-23 20:50 UTC
The current behavior of the SDK is that if QSharpDocsOutputPath is set, QSharpDocsGeneration is true by default unless explicitly set to false. This leads to bugs like microsoft/qsharp-runtime#651 when the docs path is set on the command line.

It seems surprising to me that collecting all of the docs from a solution in one folder, e.g. with `dotnet build MySolution.sln /p:QSharpDocsOutputPath=docs`, will also cause every project to generate documentation as a side-effect, so I think the default behavior should be to leave QSharpDocsGeneration as false by default regardless of QSharpDocsOutputPath.

**Comment by cgranade** [comment] 2021-04-23 20:53
This behavior was designed for consistency with the other `*Generation` MSBuild properties, such that I'd suggest changing QIR and perf data generation properties at the same time if we decide to change the defaults for `QSharpDocsGeneration`.

**Comment by bettinaheim** [comment] 2022-01-24 18:15
I'll close this as by design.

**Closed by bettinaheim** 2022-01-24 18:15 UTC
Labels: bug, area: SDK, area: docs generation
