### ISSUE TITLE
Open ended array slices are running into a type inference issue

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-compiler#1430] opened 2022-05-05 06:58 UTC
The following code results in a compiler exception from [this location](https://github.com/microsoft/qsharp-compiler/blob/f92292d6892132378cabbbb0c5113f39c76a1b1d/src/QsCompiler/Core/SyntaxGenerator.fs#L332).

```qsharp
        let arr1 = [1,2,3];
        let arr2 = [6, size = 3];

        let concatenated = arr1 + arr2;
        let slice = concatenated[arr1[0]..arr1[1]...];
```
A similar issue may exist for other open ended ranges (as part of slicing or as part of copy-and-update).

Edit: Capturing another case that seems to silently fail here since it is also an issue with open ended ranges; this may or may not be the same/a similar issue. This is the case that throws during building the compilation:
```qsharp
    operation LengthCaching (vals : Int[]) : Int[] {
        return vals[...vals[0]...];
    }
```

**Comment by ScottCarda-MS** [comment] 2022-06-27 22:23
When the Expression Verification [determines the type of array item expressions](https://github.com/microsoft/qsharp-compiler/blob/f92292d6892132378cabbbb0c5113f39c76a1b1d/src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs#L536), it seems it always assigns a type parameter as the type. I suppose this might be done because the type of the array items expressions need to be determined later on through context. This type is eventually resolved by using a InferenceContextModule.Resolver under [BuildUserDefinedImplementation](https://github.com/microsoft/qsharp-compiler/blob/f92292d6892132378cabbbb0c5113f39c76a1b1d/src/QsCompiler/CompilationManager/TypeChecking.cs#L1506).

The root of the issue is that this ultimate resolution for the type of array items expressions comes too late if an array item expression is used as a component of a slicing range expression. A slicing range expression is resolved [here](https://github.com/microsoft/qsharp-compiler/blob/f92292d6892132378cabbbb0c5113f39c76a1b1d/src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs#L446).

**Comment by ScottCarda-MS** [comment] 2022-06-27 22:33
Note that the issue is specific to the _step_ of the slicing range being derived from an array item expression, and only when one or both of the _start_ and _end_ components are missing.

**Comment by samarsha** [comment] 2022-06-27 22:54
I think the open range expansion is purely syntactic, so I'd recommend removing any checks it does on the types of the expressions.

**Comment by ScottCarda-MS** [comment] 2022-06-27 23:00
@samarsha, do you know where would be a good place to add some test cases to cover this issue?

**Closed** 2022-07-06 18:56 UTC
Labels: bug, area: type system
