### ISSUE TITLE
QIR - Cannot compile Development example in Ubuntu (in Docker) or OSX

### ISSUE THREAD

**Issue by kalzoo** [microsoft/qsharp-compiler#1063] opened 2021-06-19 02:27 UTC
**Describe the bug**

Looking to compile the example programs in this repo (under `/examples/QIR`) into QIR. Have been unable to do so either in docker (using a few MS-provided images) or on OSX. Is this intended for use on Windows only?

Is there a Dockerfile setup which would be expected to work out-of-the-box for those not familiar with the .NET ecosystem?

###  Docker w/IQ# image

Dockerfile:
```
FROM mcr.microsoft.com/quantum/iqsharp-base:0.18.2106148006

RUN git clone https://github.com/microsoft/qsharp-compiler
WORKDIR /home/jovyan/qsharp-compiler/examples/QIR/Development
RUN dotnet build
```

Error about missing GLIBC 2.29.

### Docker w/.NET 3.1 core

```
FROM mcr.microsoft.com/dotnet/sdk:3.1-focal

RUN git clone https://github.com/microsoft/qsharp-compiler

USER root
RUN apt-get update -y
RUN apt-get install -y g++ lsb-release wget software-properties-common
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 11

WORKDIR /qsharp-compiler/examples/QIR/Development
RUN dotnet build
```

Error: 

('use .NET 5.0')

```
root@c10c90e2241a:/LLVMSharp# dotnet build
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /LLVMSharp/sources/LLVMSharp/LLVMSharp.csproj (in 4.29 sec).
  Restored /LLVMSharp/sources/LLVMSharp.Interop/LLVMSharp.Interop.csproj (in 4.29 sec).
  Restored /LLVMSharp/tests/LLVMSharp.UnitTests/LLVMSharp.UnitTests.csproj (in 9.53 sec).
/usr/share/dotnet/sdk/3.1.410/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/LLVMSharp/sources/LLVMSharp/LLVMSharp.csproj]
/usr/share/dotnet/sdk/3.1.410/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/LLVMSharp/tests/LLVMSharp.UnitTests/LLVMSharp.UnitTests.csproj]
/usr/share/dotnet/sdk/3.1.410/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/LLVMSharp/sources/LLVMSharp.Interop/LLVMSharp.Interop.csproj]
  LLVMSharp.Interop -> /LLVMSharp/artifacts/bin/sources/LLVMSharp.Interop/Debug/netcoreapp3.1/LLVMSharp.Interop.dll
  LLVMSharp.Interop -> /LLVMSharp/artifacts/bin/sources/LLVMSharp.Interop/Debug/netstandard2.0/LLVMSharp.Interop.dll
  LLVMSharp -> /LLVMSharp/artifacts/bin/sources/LLVMSharp/Debug/netstandard2.0/LLVMSharp.dll
  LLVMSharp -> /LLVMSharp/artifacts/bin/sources/LLVMSharp/Debug/netcoreapp3.1/LLVMSharp.dll
  LLVMSharp.UnitTests -> /LLVMSharp/artifacts/bin/tests/LLVMSharp.UnitTests/Debug/netcoreapp3.1/LLVMSharp.UnitTests.dll

Build FAILED.

/usr/share/dotnet/sdk/3.1.410/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/LLVMSharp/sources/LLVMSharp/LLVMSharp.csproj]
/usr/share/dotnet/sdk/3.1.410/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/LLVMSharp/tests/LLVMSharp.UnitTests/LLVMSharp.UnitTests.csproj]
/usr/share/dotnet/sdk/3.1.410/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/LLVMSharp/sources/LLVMSharp.Interop/LLVMSharp.Interop.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:12.61
```

### Docker w/ .NET 5.0

```
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal

RUN git clone https://github.com/microsoft/qsharp-compiler

USER root
RUN apt-get clean && apt-get update -y
RUN apt-get install -y lsb-release wget software-properties-common
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 11


WORKDIR /qsharp-compiler/examples/QIR/Development
RUN dotnet build
```

Error:

('use .NET core 3.1')

```
#9 82.25   It was not possible to find any compatible framework version
#9 82.25   The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
#9 82.25     - The following frameworks were found:
#9 82.25         5.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
#9 82.25   
#9 82.25   You can resolve the problem by installing the specified framework and/or SDK.
```

### Docker (using QuantumKatas image)

```
jovyan@e99bb7aebdd0:~/qsharp-compiler/examples/QIR/Development$ dotnet build
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/home/jovyan/qsharp-compiler/src/Documentation/DocumentationParser/DocumentationParser.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/QirGeneration/QirGeneration.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/Compiler/Compiler.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/Compiler/Compiler.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/QirGeneration/QirGeneration.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj : error NU1101: Unable to find package CommandLineParser. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
  Restored /home/jovyan/qsharp-compiler/src/QsCompiler/DataStructures/DataStructures.fsproj (in 413 ms).
  Restored /home/jovyan/qsharp-compiler/src/QsCompiler/Core/Core.fsproj (in 414 ms).
/home/jovyan/qsharp-compiler/src/QsCompiler/BondSchemas/BondSchemas.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
  Restored /home/jovyan/qsharp-compiler/src/QsCompiler/Optimizations/Optimizations.fsproj (in 13 ms).
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/BondSchemas/BondSchemas.csproj (in 19 ms).
/home/jovyan/qsharp-compiler/src/QsCompiler/Transformations/Transformations.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
  Restored /home/jovyan/qsharp-compiler/src/QsCompiler/SyntaxProcessor/SyntaxProcessor.fsproj (in 851 ms).
/home/jovyan/qsharp-compiler/src/QsCompiler/LlvmBindings/LlvmBindings.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/Transformations/Transformations.csproj (in 389 ms).
  Failed to restore /home/jovyan/qsharp-compiler/src/Documentation/DocumentationParser/DocumentationParser.csproj (in 851 ms).
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/Compiler/Compiler.csproj (in 862 ms).
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/LlvmBindings/LlvmBindings.csproj (in 23 ms).
  Restored /home/jovyan/qsharp-compiler/src/QsCompiler/TextProcessor/TextProcessor.fsproj (in 879 ms).
/home/jovyan/qsharp-compiler/src/QsCompiler/CompilationManager/CompilationManager.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CompilationManager/CompilationManager.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj (in 879 ms).
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/QirGeneration/QirGeneration.csproj (in 879 ms).
  Failed to restore /home/jovyan/qsharp-compiler/src/QsCompiler/CompilationManager/CompilationManager.csproj (in 95 ms).
/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved.
  Restored /home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj (in 2.04 sec).

Build FAILED.

/home/jovyan/qsharp-compiler/src/QsCompiler/QirGeneration/QirGeneration.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/Compiler/Compiler.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CompilationManager/CompilationManager.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved. [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj : warning NU1603: Newtonsoft.Json.Bson 1.0.2 depends on Newtonsoft.Json (>= 12.0.1) but Newtonsoft.Json 12.0.1 was not found. An approximate best match of Newtonsoft.Json 12.0.2 was resolved.
/home/jovyan/qsharp-compiler/src/Documentation/DocumentationParser/DocumentationParser.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/Compiler/Compiler.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/QirGeneration/QirGeneration.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj : error NU1101: Unable to find package CommandLineParser. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CommandLineTool/CommandLineTool.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/BondSchemas/BondSchemas.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/Transformations/Transformations.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/LlvmBindings/LlvmBindings.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
/home/jovyan/qsharp-compiler/src/QsCompiler/CompilationManager/CompilationManager.csproj : error NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): qdk-alpha [/home/jovyan/qsharp-compiler/examples/QIR/Development/Development.csproj]
    5 Warning(s)
    9 Error(s)

Time Elapsed 00:00:07.47
```

### VSCode + OSX

1. Install .NET Core 3.1 and QDK in VSCode. 
2. Install LLVM: `brew install llvm@11`, export LD_FLAGS to match
2. Follow instructions [here](https://github.com/microsoft/qsharp-compiler/issues/1030) to attempt to compile the example
3. Receive this error:

```
➜  Development git:(main) DYLD_PRINT_LIBRARIES=1 dotnet build                        
dyld: loaded: <46395A6A-446F-3B2E-B9A7-85DD4D3F3043> /usr/local/share/dotnet/dotnet
 # ...  elided, but no reference to anything LLVM
dyld: loaded: <FE800183-AD50-3121-AC0A-FE291903C848> /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.7/libSystem.Native.dylib
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

dyld: loaded: <5E6B7F2E-609B-35E4-9052-DA29471F151A> /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.7/libSystem.Security.Cryptography.Native.Apple.dylib
  Determining projects to restore...
dyld: loaded: <AF5BC53A-B4B8-3E4D-BAFA-65501F8CCF8A> /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.7/libSystem.IO.Compression.Native.dylib
  All projects are up-to-date for restore.
  DataStructures -> ~/qsharp-compiler/src/QsCompiler/DataStructures/bin/Debug/netstandard2.1/Microsoft.Quantum.QsDataStructures.dll
  BondSchemas -> ~/qsharp-compiler/src/QsCompiler/BondSchemas/bin/Debug/netstandard2.1/Microsoft.Quantum.BondSchemas.dll
  Core -> ~/qsharp-compiler/src/QsCompiler/Core/bin/Debug/netstandard2.1/Microsoft.Quantum.QsCore.dll
  TextProcessor -> ~/qsharp-compiler/src/QsCompiler/TextProcessor/bin/Debug/netstandard2.1/Microsoft.Quantum.QsTextProcessor.dll
  Optimizations -> ~/qsharp-compiler/src/QsCompiler/Optimizations/bin/Debug/netstandard2.1/Microsoft.Quantum.QsOptimizations.dll
  Transformations -> ~/qsharp-compiler/src/QsCompiler/Transformations/bin/Debug/netstandard2.1/Microsoft.Quantum.QsTransformations.dll
  DocumentationParser -> ~/qsharp-compiler/src/Documentation/DocumentationParser/bin/Debug/netstandard2.1/Microsoft.Quantum.QsDocumentationParser.dll
  SyntaxProcessor -> ~/qsharp-compiler/src/QsCompiler/SyntaxProcessor/bin/Debug/netstandard2.1/Microsoft.Quantum.QsSyntaxProcessor.dll
  CompilationManager -> ~/qsharp-compiler/src/QsCompiler/CompilationManager/bin/Debug/netstandard2.1/Microsoft.Quantum.QsCompilationManager.dll
  Compiler -> ~/qsharp-compiler/src/QsCompiler/Compiler/bin/Debug/netstandard2.1/Microsoft.Quantum.QsCompiler.dll
  CommandLineTool -> ~/qsharp-compiler/src/QsCompiler/CommandLineTool/bin/Debug/netcoreapp3.1/qsc.dll
  LlvmBindings -> ~/qsharp-compiler/src/QsCompiler/LlvmBindings/bin/Debug/netstandard2.1/Microsoft.Quantum.LlvmBindings.dll
  QirGeneration -> ~/qsharp-compiler/src/QsCompiler/QirGeneration/bin/Debug/netstandard2.1/Microsoft.Quantum.QirGeneration.dll
  Determining projects to restore...
  All projects are up-to-date for restore.
  Removed files from prior compilation.
  : info: 
  System.TypeInitializationException: The type initializer for 'Microsoft.Quantum.QsCompiler.QIR.GenerationContext' threw an exception.
   ---> System.DllNotFoundException: Unable to load shared library 'libLLVM' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibLLVM, 1): image not found
     at LLVMSharp.Interop.LLVM.InstallFatalErrorHandler(IntPtr Handler)
     at Ubiquity.NET.Llvm.Interop.Library.InitializeLLVM() in ~/qsharp-compiler/src/QsCompiler/LlvmBindings/Library.cs:line 66
     at Microsoft.Quantum.QsCompiler.QIR.GenerationContext..cctor() in ~/qsharp-compiler/src/QsCompiler/QirGeneration/Context.cs:line 39
     --- End of inner exception stack trace ---
     at Microsoft.Quantum.QsCompiler.QIR.GenerationContext..ctor(IEnumerable`1 syntaxTree) in ~/qsharp-compiler/src/QsCompiler/QirGeneration/Context.cs:line 108
     at Microsoft.Quantum.QsCompiler.QirGeneration.Transformation(QsCompilation compilation, QsCompilation& transformed) in ~/qsharp-compiler/src/QsCompiler/QirGeneration/RewriteSteps.cs:line 77
     at Microsoft.Quantum.QsCompiler.LoadedStep.Transformation(QsCompilation compilation, QsCompilation& transformed) in ~/qsharp-compiler/src/QsCompiler/Compiler/LoadedStep.cs:line 209
     at Microsoft.Quantum.QsCompiler.CompilationLoader.ExecuteRewriteStep(LoadedStep rewriteStep, QsCompilation compilation, QsCompilation& transformed) in ~/qsharp-compiler/src/QsCompiler/Compiler/CompilationLoader.cs:line 919
  
EXEC(1,1): error QS7109: The compilation step "QIR Generation" loaded from "~/qsharp-compiler/src/QsCompiler/QirGeneration/bin/Debug/netstandard2.1/Microsoft.Quantum.QirGeneration.dll" threw an exception. [~/qsharp-compiler/examples/QIR/Development/Development.csproj]
  
  ____________________________________________
  
  Q# compilation failed: 1 error, 0 warnings 
  1 logged exception
  
~/.nuget/packages/microsoft.quantum.sdk/0.16.2105142080-alpha/Sdk/Sdk.targets(151,5): error MSB3073: The command "dotnet ~/qsharp-compiler/examples/QIR/Development/../../../src/QsCompiler/CommandLineTool/bin/Debug/netcoreapp3.1/qsc.dll build --format MsBuild -v Normal --response-files obj/qsharp/config/qsc.rsp" exited with code 246. [~/qsharp-compiler/examples/QIR/Development/Development.csproj]
~/.nuget/packages/microsoft.quantum.sdk/0.16.2105142080-alpha/Sdk/Sdk.targets(156,5): error : Q# compiler failed with exit code: 246. [~/qsharp-compiler/examples/QIR/Development/Development.csproj]

Build FAILED.

EXEC(1,1): error QS7109: The compilation step "QIR Generation" loaded from "~/qsharp-compiler/src/QsCompiler/QirGeneration/bin/Debug/netstandard2.1/Microsoft.Quantum.QirGeneration.dll" threw an exception. [~/qsharp-compiler/examples/QIR/Development/Development.csproj]
~/.nuget/packages/microsoft.quantum.sdk/0.16.2105142080-alpha/Sdk/Sdk.targets(151,5): error MSB3073: The command "dotnet ~/qsharp-compiler/examples/QIR/Development/../../../src/QsCompiler/CommandLineTool/bin/Debug/netcoreapp3.1/qsc.dll build --format MsBuild -v Normal --response-files obj/qsharp/config/qsc.rsp" exited with code 246. [~/qsharp-compiler/examples/QIR/Development/Development.csproj]
~/.nuget/packages/microsoft.quantum.sdk/0.16.2105142080-alpha/Sdk/Sdk.targets(156,5): error : Q# compiler failed with exit code: 246. [~/qsharp-compiler/examples/QIR/Development/Development.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:06.65
```

**System information**

- OSX 10.15.7, and different ubuntu base images as shown above

**Comment by kalzoo** [comment] 2021-06-20 01:18
FWIW, it runs right out-of-the-box in windows using vagrant. For those interested:

```
vagrant init 'gusztavvargadr/visual-studio'
vagrant up
vagrant ssh
choco install git
refreshenv
git clone https://github.com/microsoft/qsharp-compiler --depth 1
cd qsharp-compiler\examples\QIR\Development
dotnet build
type qir\Development.ll
```

Note that `dotnet build` failed on the `Development` example due to missing clang++ dependency, but generated the needed `.ll` file. `Emission` build worked without issue.

**Comment by bettinaheim** [comment] 2021-06-29 01:12
@kalzoo While it is expected that the docker images fail (I don't believe they would contain the necessary llvm libs), the Development project was meant to build on Mac and Linux as well. Looking at the corresponding error, it looks like it is not finding these as it should (libLLVM). Could you please check if in the obj/qsharp/config/qsc.rsp file, the --llvm-libs argument is specified, and whether the path that is listed for it indeed contains the libLLVM library (in a subfolder runtime/os_x64/native/)?

**Comment by bettinaheim** [comment] 2021-07-08 07:47
I can reproduce it after launching it in a clean linux container without llvm installed (clang installed via apt install). The issue is that when the QirGeneration rewrite step is loaded via reflection (which is usually only the case if the rewrite step is loaded from within by a compiler version that is newer than the one against which the rewrite step has been built - but also is the case for the Development project) then on linux it is only looking for the llvm libs in the system libraries (i.e. under /usr/, /lib/, /etc/, but not in the directory of the current application) rather than being able to find it via the path that is passed to the command line compiler. What I currently cannot seem to figure out at this time is how to convince it to look somewhere else. 
The only thing that I could get to work so far is to manually put the libLLVM.so under /usr/lib/ where it is already looking.

**Comment by cgranade** [comment] 2021-07-08 14:34
@bettinaheim: I've had good luck using [custom DLL resolvers](https://docs.microsoft.com/dotnet/standard/native-interop/cross-platform) in similar scenarios before, as that allows for intercepting native library loads and redirecting them to a path of your choosing.

**Comment by cgranade** [comment] 2021-07-08 17:04
Ah, got it. If the native library is loaded in an assembly outside our control, that is a much harder problem to solve, agreed. The native DLL resolver is assembly-local such that setting a resolver won't work for native libraries loaded by LlvmSharp... let me think on that, then...

**Comment by bettinaheim** [comment] 2021-07-08 17:15
What I know works is if you load it a separate context (which is done by default, unless the rewrite step was compiled against a different compiler version). In that case, preloading the llvm libs via context.LoadUnmanagedDllFromPath(pathtollvmlibs) works perfectly fine. I don't seem to have the means to do something similar for the current app context though...

**Comment by bettinaheim** [comment] 2022-01-22 02:41
This should be largely addressed by https://github.com/microsoft/qsharp-compiler/pull/1269, with the caveat listed in the readme.

**Closed by bettinaheim** 2022-01-22 02:41 UTC
Labels: bug, area: QIR
