### ISSUE TITLE
Language server stops working after adding a new file

### ISSUE THREAD

**Issue by anpaz** [microsoft/qsharp-compiler#720] opened 2020-11-03 17:58 UTC
**Describe the bug**

The language server randomly crashes while working on a Q# project in VS Code. When it does, it will not restart until VS Code re-opened and closed.

**To Reproduce**

Create a new Q# project. This particular one had a couple of not very big files (a couple of operations each). As I was working in VS Code I would get this Exception:

```
[Error - 11:11:46 PM] 
=============================
Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
NullReferenceException: Object reference not set to an instance of an object.
Stack trace: 
at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.PushChange(TextDocumentContentChangeEvent change, Boolean& publishDiagnostics) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 999
at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.ReplaceFileContent(String text) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 1053
at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass18_0.<AddOrUpdateSourceFileAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 275
at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56

at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProcessingQueue.<>c__DisplayClass4_0.<ProcessingTaskAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ProcessingQueue.cs:line 48
=============================
```

**System information**

- **VS Code:** 1.50.1
- **Extension:** 0.13.20102604
- **OS:** Mac OSX Catalina
- **.NET Core:** 3..403

**Comment by anpaz** [comment] 2020-11-03 21:29
A little more information: looks like the server is actually not crashing, but every key entered generates the same information so everything stops working (auto-complete, code actions, hovering, etc). Saving a file doesn't fix the problem.

I am able to reproduce the same problem in Windows too. These are my steps:
* Create new Q# library project, open in VS Code.
* Open the Library.qs file to get the Q# extension started. 
* Once ready, add a new .qs file, open the file.
* Add a namespace, an operation and start editing the operation, something like this:
```
namespace foo {
    open Microsoft.Quantum.Intrinsic;
    open Microsoft.Quantum.Canon;

    // ...
    operation Bar(target : Qubit) : Unit
    is Adj + Ctl {
        // ...
        let =
    }

}
```

by the time I start writting `let =` I start seeing the exceptions in the output window.

**Comment by samarsha** [comment] 2020-11-03 22:59
Could you post the full log from the "Q# Language Extension" output? When I try to reproduce this, I noticed this happens:

```
[Info  - 14:53:14] workspace folder: c:\Users\samarsha\Desktop\Library
Discovered Q# project 'c:\Users\samarsha\Desktop\Library\Library.csproj'.
Loading project 'c:\Users\samarsha\Desktop\Library\Library.csproj'.
Done loading project 'c:\Users\samarsha\Desktop\Library\Library.csproj'
Discovered Q# project 'C:\Users\samarsha\AppData\Local\Temp\qsharp\c_x2f__x2f_Users_x2f_samarsha_x2f_Desktop_x2f_Library\generated.csproj'.
Loading project 'C:\Users\samarsha\AppData\Local\Temp\qsharp\c_x2f__x2f_Users_x2f_samarsha_x2f_Desktop_x2f_Library\generated.csproj'.
The file c:\Users\samarsha\Desktop\Library\Library.qs has been associated with the compilation unit C:\Users\samarsha\AppData\Local\Temp\qsharp\c_x2f__x2f_Users_x2f_samarsha_x2f_Desktop_x2f_Library\generated.csproj.
Done loading project 'C:\Users\samarsha\AppData\Local\Temp\qsharp\c_x2f__x2f_Users_x2f_samarsha_x2f_Desktop_x2f_Library\generated.csproj'
Discovered Q# project 'c:\Users\samarsha\Desktop\Library\Library.csproj'.
Loading project 'c:\Users\samarsha\Desktop\Library\Library.csproj'.
The file c:\Users\samarsha\Desktop\Library\Foo.qs has been associated with the compilation unit c:\Users\samarsha\Desktop\Library\Library.csproj.
Done loading project 'c:\Users\samarsha\Desktop\Library\Library.csproj'
```

which could be causing issues, because the language server should not be generating a temporary Q# project for a file that is already part of an existing Q# project. After this, I get some NullReferenceExceptions as well, but they're different from the one you're getting:

```
Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
QsCompilerException: error during scope tracking update
NullReferenceException: Object reference not set to an instance of an object.
Stack trace: 
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.DequeueUnprocessedChanges(Int32& lineNr, String& textToInsert) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 924
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ScopeTracking.UpdateScopeTacking(FileContentManager file, TextDocumentContentChangeEvent change) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ScopeTracking.cs:line 733
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.<>c__DisplayClass68_0.<Update>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 944
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56

Stack trace: 
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.Update(TextDocumentContentChangeEvent change) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 945
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.PushChange(TextDocumentContentChangeEvent change, Boolean& publishDiagnostics) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 1035
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass20_0.<SourceFileDidChangeAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 327
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56

   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProcessingQueue.<>c__DisplayClass4_0.<ProcessingTaskAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ProcessingQueue.cs:line 42
```

**Comment by samarsha** [comment] 2020-11-03 23:01
Also, if you close VS Code and re-open the library you created earlier, does the problem still happen? Or does it only happen if you create a new project and file, and open them in the same session?

**Comment by anpaz** [comment] 2020-11-04 19:11
Here is all the logs up to the first couple of errors (let me know if you need more, but there is an stack trace for every key I stroke afterwards):

```
[Info  - 11:06:45 AM] workspace folder: c:\Repos\Temp\ls
Discovered Q# project 'c:\Repos\Temp\ls\ls.csproj'.
Loading project 'c:\Repos\Temp\ls\ls.csproj'.
Done loading project 'c:\Repos\Temp\ls\ls.csproj'
Discovered Q# project 'C:\Users\anpaz\AppData\Local\Temp\qsharp\c_x2f__x2f_Repos_x2f_Temp_x2f_ls\generated.csproj'.
Loading project 'C:\Users\anpaz\AppData\Local\Temp\qsharp\c_x2f__x2f_Repos_x2f_Temp_x2f_ls\generated.csproj'.
The file c:\Repos\Temp\ls\Library.qs has been associated with the compilation unit C:\Users\anpaz\AppData\Local\Temp\qsharp\c_x2f__x2f_Repos_x2f_Temp_x2f_ls\generated.csproj.
Done loading project 'C:\Users\anpaz\AppData\Local\Temp\qsharp\c_x2f__x2f_Repos_x2f_Temp_x2f_ls\generated.csproj'
Discovered Q# project 'c:\Repos\Temp\ls\ls.csproj'.
Loading project 'c:\Repos\Temp\ls\ls.csproj'.
The file c:\Repos\Temp\ls\bar.qs has been associated with the compilation unit c:\Repos\Temp\ls\ls.csproj.
Done loading project 'c:\Repos\Temp\ls\ls.csproj'
[Error - 11:09:32 AM] 
=============================
Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
QsCompilerException: error during scope tracking update
ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'startChar')
Stack trace: 
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.Utils.GetChangedText(String lineText, Int32 startChar, Int32 endChar, String insert) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\Utils.cs:line 118
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.DequeueUnprocessedChanges(Int32& lineNr, String& textToInsert) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 924
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ScopeTracking.UpdateScopeTacking(FileContentManager file, TextDocumentContentChangeEvent change) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ScopeTracking.cs:line 733
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.<>c__DisplayClass68_0.<Update>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 944
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 54

Stack trace: 
   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.Update(TextDocumentContentChangeEvent change) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 945
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.PushChange(TextDocumentContentChangeEvent change, Boolean& publishDiagnostics) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 1035
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass20_0.<SourceFileDidChangeAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 327
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 54

   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProcessingQueue.<>c__DisplayClass4_0.<ProcessingTaskAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ProcessingQueue.cs:line 42
=============================

[Error - 11:09:38 AM] 
=============================
Microsoft.Quantum.QsCompiler.QsCompilerException: error while running queued task
InvalidOperationException: Collection was modified after the enumerator was instantiated.
Stack trace: 
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.FileContentManager.PushChange(TextDocumentContentChangeEvent change, Boolean& publishDiagnostics) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\FileContentManager.cs:line 1001
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.CompilationUnitManager.<>c__DisplayClass20_0.<SourceFileDidChangeAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\CompilationUnitManager.cs:line 327
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56

   at Microsoft.Quantum.QsCompiler.QsCompilerError.Raise(String message, Exception innerException) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 27
   at Microsoft.Quantum.QsCompiler.QsCompilerError.RaiseOnFailure(Action action, String header) in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\DataStructures\ErrorHandling.fs:line 56
   at Microsoft.Quantum.QsCompiler.CompilationBuilder.ProcessingQueue.<>c__DisplayClass4_0.<ProcessingTaskAsync>b__0() in D:\a\1\s\submodules\qsharp-compiler\src\QsCompiler\CompilationManager\ProcessingQueue.cs:line 48
=============================
```

**Comment by rmshaffer** [comment] 2020-11-11 15:36
This has been mitigated by #731. However, note that even with that change, this issue still reproduces in the following scenario:

- Create new Q# library project, open in VS Code.
- Open the Library.qs file to get the Q# extension started.
- Add a new .csproj file to the folder (e.g., by duplicating the existing .csproj). Wait for the Q# extension to load it.
- Once ready, add a new .qs file, open the file.
- Add a namespace, an operation and start editing the operation.

The underlying problem seems to be that the extension is associating the new .qs file with multiple .csproj files.

**Comment by bettinaheim** [comment] 2020-11-13 03:30
@rmshaffer Since the Sdk indeed automatically pulls in all .qs files in that folder, the .qs file indeed according to the description of your setup *is* associated with both projects. 
That this is not supported is a known limitation of the server which might be nice to address, but e.g. addressing the limitation of projects outside the solution folder being invisible to the server should be higher on the priority list. The decision to impose that a file cannot be associate with multiple projects, like the decision that only the workspace folder is considered, or that you cannot have the same files open multiple times in the IDE are by design (which doesn't mean it wouldn't be nice to alleviate the restriction in the future). 
Hence I will close this issue (the bug that adding a file causes a crash is remedied). I'll leave it up to you to file enhancement requests for the scenarios that I mentioned above if you would like to capture them on GitHub (the decision on what limitations we impose predates the public repo).

**Closed by bettinaheim** 2020-11-13 03:30 UTC
Labels: Area-IDE, bug

**Comment by rmshaffer** [comment] 2020-11-13 03:43
Thanks @bettinaheim, understood. I did not mean to make a feature request, but I just thought it would be informative to list an additional scenario where this crash occurs in case someone runs into it in the future.

**Comment by bettinaheim** [comment] 2020-11-14 01:36
@rmshaffer It should be documented somewhere, but seeing how much docs changed (and that people now are more likely to look here), giving a descriptive error message would make sense. I filed a separate issue for that: https://github.com/microsoft/qsharp-compiler/issues/740
I'd rather not invest into handling the case, since the amount of work compared to the benefit is unreasonable.
